### ISSUE TITLE
How were the CSV files generated?

### ISSUE THREAD

**Issue by zcxsythenew** [yigitsever/kubernetes-dataset#1]
Hi, could you please tell me how were the CSV files generated? From the filenames (such as "background_traffic_20230319T1802.**pcap**_Flow.csv") I assume that the data were pcaps originally. Which tools were used to generate the CSV files?

**Comment by yigitsever** [comment]
The repository is supplementary to the paper [A Kubernetes dataset for misuse detection](https://www.itu.int/pub/S-JNL-VOL4.ISSUE2-2023-A26), I was meaning to write a proper README to reflect that

The flow files were generated by [this fork of CICFlowMeter](https://github.com/GintsEngelen/CICFlowMeter)

**Comment by zcxsythenew** [comment]
Will the raw pcaps be released?

**Comment by yigitsever** [comment]
The raw .pcaps are around 280GB~ compressed, I can surely host them somewhere if needed but the .pcap generation steps are documented in the paper linked above (and I can clarify anything if needed) so you can follow them to generate .pcaps as well
